# Generated by Django 3.2.2 on 2021-05-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='動画ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('tab', models.CharField(blank=True, max_length=255, null=True, verbose_name='TAB')),
                ('has_solo', models.BooleanField(default=False, verbose_name='ソロ？')),
                ('solo_start_seconds', models.IntegerField(blank=True, null=True, verbose_name='ソロ開始秒')),
                ('posted_at_on_patreon', models.DateField(blank=True, null=True, verbose_name='Patreon投稿日')),
                ('posted_at_on_youtube', models.DateField(blank=True, null=True, verbose_name='YouTube投稿日')),
                ('title_on_youtube', models.CharField(blank=True, max_length=255, null=True, verbose_name='YouTube上のタイトル')),
                ('scale', models.CharField(blank=True, max_length=50, null=True, verbose_name='スケール')),
                ('key', models.CharField(blank=True, max_length=10, null=True, verbose_name='キー')),
                ('chord_progression', models.TextField(blank=True, null=True, verbose_name='コード進行')),
                ('description', models.TextField(blank=True, null=True, verbose_name='説明文')),
            ],
            options={
                'db_table': 'videos',
            },
        ),
    ]
