# Generated by Django 3.2.3 on 2021-05-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-posted_at_on_youtube']},
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='thumbnails/', verbose_name='サムネイル'),
        ),
    ]
