# Generated by Django 3.2.3 on 2021-05-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0002_auto_20210515_2007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-posted_at']},
        ),
        migrations.RemoveField(
            model_name='video',
            name='posted_at_on_patreon',
        ),
        migrations.RemoveField(
            model_name='video',
            name='posted_at_on_youtube',
        ),
        migrations.RemoveField(
            model_name='video',
            name='title_on_youtube',
        ),
        migrations.AddField(
            model_name='video',
            name='posted_at',
            field=models.DateField(blank=True, null=True, verbose_name='投稿日'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/', verbose_name='サムネイル'),
        ),
    ]
