# Generated by Django 3.2.3 on 2021-05-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0003_auto_20210516_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='title_on_youtube',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='YouTube上のタイトル'),
        ),
    ]
